// AXIS — Disinformation Detection Module
// © 2026 Kuzey Çağan Gebrecioğlu

var DISINFO_INDICATORS={sourceReliability:{"reuters.com":95,"apnews.com":95,"afp.com":92,"bbc.com":88,"bbc.co.uk":88,"dw.com":85,"france24.com":85,"aljazeera.com":80,"nhk.or.jp":88,"nytimes.com":82,"washingtonpost.com":80,"theguardian.com":82,"lemonde.fr":83,"spiegel.de":82,"economist.com":88,"ft.com":87,"rt.com":25,"sputniknews.com":20,"tass.com":30,"globaltimes.cn":30,"xinhua.net":35,"cgtn.com":32,"presstv.ir":20,"irna.ir":25,"aa.com.tr":55,"trt.net.tr":50,"dailysabah.com":50,"infowars.com":5,"zerohedge.com":15,"breitbart.com":20,"globalresearch.ca":10,"southfront.org":10},manipulationPatterns:{emotional_loading:{keywords:["BREAKING","SHOCKING","DEVASTATING","HORRIFIC","EXCLUSIVE","URGENT","BOMBSHELL"],weight:.3,desc:{en:"Emotional loading / sensationalism",tr:"Duygusal yükleme / sansasyonelizm"}},false_binary:{keywords:["EITHER","ONLY OPTION","NO CHOICE BUT"],weight:.4,desc:{en:"False binary framing",tr:"Sahte ikili çerçeveleme"}},attribution_manipulation:{keywords:["SOURCES SAY","REPORTEDLY","IT IS BELIEVED","EXPERTS CLAIM","SOME SAY"],weight:.2,desc:{en:"Vague attribution",tr:"Belirsiz atıf"}},whataboutism:{keywords:["WHAT ABOUT","BUT THEY ALSO","HYPOCRISY","DOUBLE STANDARD"],weight:.3,desc:{en:"Whataboutism / deflection",tr:"Whataboutism / saptırma"}},dehumanization:{keywords:["ANIMALS","VERMIN","BARBARIANS","SAVAGES","SUBHUMAN"],weight:.5,desc:{en:"Dehumanization language",tr:"İnsanlıktan çıkarma dili"}},conspiracy_framing:{keywords:["DEEP STATE","NEW WORLD ORDER","PUPPET","ORCHESTRATED","CABAL","GLOBALIST"],weight:.5,desc:{en:"Conspiracy framing",tr:"Komplo çerçevelemesi"}},fear_amplification:{keywords:["THREAT TO CIVILIZATION","EXISTENTIAL","ANNIHILATE","EXTINCTION","TOTAL WAR"],weight:.4,desc:{en:"Fear amplification",tr:"Korku büyütme"}}},knownCampaigns:{RU:{targets:["US","DE","FR","GB"],methods:{en:["Bot networks","RT/Sputnik","Social media manipulation","Hack-and-leak"],tr:["Bot ağları","RT/Sputnik","Sosyal medya manipülasyonu","Hack ve sızdırma"]},themes:{en:["NATO aggression","Western decline","Election interference"],tr:["NATO saldırganlığı","Batı çöküşü","Seçim müdahalesi"]}},CN:{targets:["US","AU","JP","IN"],methods:{en:["Wolf warrior diplomacy","CGTN/Xinhua","TikTok algorithm"],tr:["Kurt savaşçı diplomasisi","CGTN/Xinhua","TikTok algoritması"]},themes:{en:["Taiwan is China","Xinjiang counter-narrative","US decline"],tr:["Tayvan Çin'dir","Sinciang karşı-anlatı","ABD çöküşü"]}},IR:{targets:["US","SA"],methods:{en:["Press TV","Social media sock puppets"],tr:["Press TV","Sahte hesaplar"]},themes:{en:["Resistance axis","Anti-Zionism","US imperialism"],tr:["Direniş ekseni","Anti-Siyonizm","ABD emperyalizmi"]}}}};

function extractDomain(url){try{if(url.indexOf("http")!==0)url="https://"+url;return new URL(url).hostname.replace("www.","")}catch(e){return url}}

function analyzeDisinfo(articles,codeA,codeB){if(!articles||articles.length===0)return null;var results={totalArticles:articles.length,reliabilityAvg:0,flaggedArticles:[],patternCounts:{},sourceDistribution:{tier1:0,tier2:0,tier3_state:0,tier4_disinfo:0},overallRisk:0,campaigns:[]};
articles.forEach(function(art){var domain=extractDomain(art.url||art.domain||"");var rel=DISINFO_INDICATORS.sourceReliability[domain]||50;results.reliabilityAvg+=rel;if(rel>=80)results.sourceDistribution.tier1++;else if(rel>=55)results.sourceDistribution.tier2++;else if(rel>=25)results.sourceDistribution.tier3_state++;else results.sourceDistribution.tier4_disinfo++;
var title=(art.title||"").toUpperCase();var flags=[];Object.entries(DISINFO_INDICATORS.manipulationPatterns).forEach(function(e){var found=e[1].keywords.some(function(kw){return title.indexOf(kw)>=0});if(found){flags.push(e[0]);results.patternCounts[e[0]]=(results.patternCounts[e[0]]||0)+1}});if(rel<35||flags.length>=2)results.flaggedArticles.push({title:art.title,source:domain,reliability:rel,flags:flags})});
results.reliabilityAvg=Math.round(results.reliabilityAvg/Math.max(1,articles.length));
[codeA,codeB].forEach(function(code){Object.entries(DISINFO_INDICATORS.knownCampaigns).forEach(function(e){if(e[1].targets.indexOf(code)>=0)results.campaigns.push({actor:e[0],target:code,methods:lang==="tr"?e[1].methods.tr:e[1].methods.en,themes:lang==="tr"?e[1].themes.tr:e[1].themes.en})})});
var stR=results.sourceDistribution.tier3_state/Math.max(1,articles.length);var diR=results.sourceDistribution.tier4_disinfo/Math.max(1,articles.length);var pC=Object.values(results.patternCounts).reduce(function(s,v){return s+v},0);results.overallRisk=Math.min(100,Math.round((100-results.reliabilityAvg)*.3+stR*100*.25+diR*100*.25+Math.min(50,pC*5)*.2));return results}

function renderDisinfoCard(analysis){if(!analysis)return"";var t=lang==="tr";var rc=analysis.overallRisk>=60?"var(--neg)":analysis.overallRisk>=35?"var(--amber)":"var(--green)";var rl=analysis.overallRisk>=60?(t?"YÜKSEK RİSK":"HIGH RISK"):analysis.overallRisk>=35?(t?"ORTA RİSK":"MEDIUM RISK"):(t?"DÜŞÜK RİSK":"LOW RISK");
var h='<div style="background:var(--card-bg);border:1px solid var(--border);border-left:3px solid '+rc+';border-radius:2px;padding:16px;margin-bottom:20px">';h+='<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span style="color:'+rc+'">'+(ICONS&&ICONS.disinfo?ICONS.disinfo:"🔍")+'</span><span style="font-family:var(--font-mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:'+rc+'">'+(t?"Bilgi Bütünlüğü Analizi":"Information Integrity Analysis")+'</span><span style="margin-left:auto;font-family:var(--font-mono);font-size:1.2rem;font-weight:700;color:'+rc+'">'+analysis.overallRisk+'</span></div>';
h+='<div class="disc-score-bar"><div class="disc-score-fill" style="width:'+analysis.overallRisk+'%;background:'+rc+'"></div></div><div class="disc-verdict" style="color:'+rc+'">'+rl+'</div>';
h+='<div class="disinfo-sub-title">'+(t?"Kaynak Güvenilirlik Dağılımı":"Source Reliability Distribution")+' ('+analysis.totalArticles+' '+(t?"haber":"articles")+')</div><div class="disinfo-dist">';var tot=analysis.totalArticles||1;h+=dBar(t?"Güvenilir Ajanslar":"Reliable Agencies",analysis.sourceDistribution.tier1,tot,"var(--green)");h+=dBar(t?"Ulusal Yayınlar":"National Outlets",analysis.sourceDistribution.tier2,tot,"var(--cyan)");h+=dBar(t?"Devlet Medyası":"State Media",analysis.sourceDistribution.tier3_state,tot,"var(--amber)");h+=dBar(t?"Dezenformasyon Riski":"Disinfo Risk",analysis.sourceDistribution.tier4_disinfo,tot,"var(--neg)")+'</div>';
if(Object.keys(analysis.patternCounts).length>0){h+='<div class="disinfo-sub-title">'+(t?"Tespit Edilen Kalıplar":"Detected Patterns")+'</div>';Object.entries(analysis.patternCounts).sort(function(a,b){return b[1]-a[1]}).forEach(function(e){var p=DISINFO_INDICATORS.manipulationPatterns[e[0]];if(p)h+='<div class="disinfo-pattern-row"><span class="disinfo-pattern-name">'+(t?p.desc.tr:p.desc.en)+'</span><span class="disinfo-pattern-count">'+e[1]+'x</span></div>'})}
if(analysis.campaigns.length>0){h+='<div class="disinfo-sub-title">'+(t?"⚠ Bilinen Dezenformasyon Vektörleri":"⚠ Known Disinfo Vectors")+'</div>';analysis.campaigns.forEach(function(camp){h+='<div class="disinfo-campaign"><div class="disinfo-camp-header"><img src="https://flagcdn.com/w20/'+(_flagMap[camp.actor]||camp.actor.toLowerCase())+'.png" width="14" height="9"> '+(C[camp.actor]?C[camp.actor].n:camp.actor)+' → '+(C[camp.target]?C[camp.target].n:camp.target)+'</div><div class="disinfo-camp-methods">'+(t?"Yöntemler: ":"Methods: ")+camp.methods.join(", ")+'</div><div class="disinfo-camp-themes">'+(t?"Temalar: ":"Themes: ")+camp.themes.join(", ")+'</div></div>'})}
if(analysis.flaggedArticles.length>0){h+='<div class="disinfo-sub-title">'+(t?"🚩 Bayraklı Haberler":"🚩 Flagged Articles")+'</div>';analysis.flaggedArticles.slice(0,5).forEach(function(art){h+='<div class="disinfo-flagged-item"><div class="disinfo-flagged-title">'+(art.title||"").substring(0,80)+'</div><div class="disinfo-flagged-meta"><span class="disinfo-flagged-source">'+art.source+'</span><span class="disinfo-flagged-score" style="color:'+(art.reliability<30?"var(--neg)":"var(--amber)")+'">'+(t?"Güvenilirlik: ":"Reliability: ")+art.reliability+'/100</span></div></div>'})}
h+='<div class="disc-ai-section"><button class="disc-ai-btn" onclick="runDisinfoAI()" '+(getGroqKey()?"":"disabled")+'>🧠 '+(t?"AI Dezenformasyon Analizi":"AI Disinformation Analysis")+'</button><div id="disinfoAiResult"></div></div></div>';return h}

function dBar(label,count,total,color){var pct=Math.round(count/total*100);return'<div class="disinfo-dist-row"><span class="disinfo-dist-label">'+label+'</span><div class="disinfo-dist-track"><div class="disinfo-dist-fill" style="width:'+pct+'%;background:'+color+'"></div></div><span class="disinfo-dist-val" style="color:'+color+'">'+count+' ('+pct+'%)</span></div>'}

var lastDisinfoAnalysis=null;
function triggerDisinfoAnalysis(codeA,codeB){try{var key=gdeltCacheKey(codeA,codeB);var cached=sessionStorage.getItem(key);if(!cached)return"";var gd=JSON.parse(cached);if(!gd.recentArticles||gd.recentArticles.length===0)return"";lastDisinfoAnalysis=analyzeDisinfo(gd.recentArticles,codeA,codeB);return renderDisinfoCard(lastDisinfoAnalysis)}catch(e){return""}}

async function runDisinfoAI(){var el=document.getElementById("disinfoAiResult");if(!el||!lastDisinfoAnalysis)return;var key=getGroqKey();var t=lang==="tr";if(!key){el.innerHTML='<div class="disc-ai-err">'+T("aiNoKey")+'</div>';return}el.innerHTML='<div class="disc-ai-loading">'+(t?"DEZENFORMASYON ANALİZİ...":"DISINFORMATION ANALYSIS...")+'</div>';var a=lastDisinfoAnalysis;var s="Disinfo analysis: "+a.totalArticles+" articles, avg reliability: "+a.reliabilityAvg+"/100, risk: "+a.overallRisk+"/100\nSources: T1="+a.sourceDistribution.tier1+", T2="+a.sourceDistribution.tier2+", State="+a.sourceDistribution.tier3_state+", Disinfo="+a.sourceDistribution.tier4_disinfo;if(a.campaigns.length>0)s+="\nCampaigns: "+a.campaigns.map(function(c){return c.actor+"→"+c.target}).join(", ");try{var text=await callGroq("You are AXIS, a disinformation analyst. Assess info environment: 1) State manipulation 2) Propaganda patterns 3) Source health 4) Counter-measures. Write in "+(t?"Turkish":"English")+". Under 200 words.",s);el.innerHTML='<div class="disc-ai-text">'+text.replace(/\n/g,"<br>")+'</div><div class="disc-ai-disclaimer">'+T("aiDisclaimer")+'</div>'}catch(e){el.innerHTML='<div class="disc-ai-err">'+T("aiError")+'</div>'}}