// AXIS — Advanced Engine UI Renderer
// © 2026 Kuzey Çağan Gebrecioğlu

function renderAdvancedAnalysis(codeA,codeB){var adv;try{adv=computeAxisAdvanced(codeA,codeB)}catch(e){console.warn("Adv analysis failed:",e);return""}if(!adv)return"";var t=lang==="tr";var h="";

// Warnings
if(adv.warnings&&adv.warnings.length>0){h+='<div class="eng-warnings">';adv.warnings.forEach(function(w){var crit=w.indexOf("THUCYDIDES")>=0||w.indexOf("NÜKLEER")>=0||w.indexOf("NUCLEAR")>=0||w.indexOf("BOĞAZ")>=0||w.indexOf("CHOKEPOINT")>=0;h+='<div class="eng-warn-item'+(crit?" critical":"")+'">'+w+'</div>'});h+='</div>'}

// Monte Carlo
var mc=adv.monteCarlo;if(mc){h+='<div style="background:var(--card-bg);border:1px solid var(--border);border-left:3px solid var(--cyan);border-radius:2px;padding:16px;margin-bottom:8px">';h+='<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span style="color:var(--cyan)">'+(ICONS&&ICONS.montecarlo?ICONS.montecarlo:"📊")+'</span><span style="font-family:var(--font-mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:var(--cyan)">'+(t?"Monte Carlo Belirsizlik":"Monte Carlo Uncertainty")+'</span><span style="margin-left:auto;font-family:var(--font-mono);font-size:1rem;font-weight:700;color:var(--t1)">'+mc.mean+' ±'+mc.stdDev+'</span></div>';
h+='<div class="mc-dist"><div class="mc-dist-bar"><div class="mc-ci95" style="left:'+mc.ci95[0]+'%;width:'+(mc.ci95[1]-mc.ci95[0])+'%"></div><div class="mc-ci80" style="left:'+mc.ci80[0]+'%;width:'+(mc.ci80[1]-mc.ci80[0])+'%"></div><div class="mc-mean-dot" style="left:'+mc.mean+'%"></div></div><div class="mc-dist-labels"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div></div>';
h+='<div class="mc-stats"><span class="mc-stat">'+(t?"Ort":"Mean")+': <b>'+mc.mean+'</b></span><span class="mc-stat">σ: <b>'+mc.stdDev+'</b></span><span class="mc-stat">'+(t?"Sağlamlık":"Robustness")+': <b style="color:'+(mc.robustness==="high"?"var(--green)":mc.robustness==="medium"?"var(--amber)":"var(--neg)")+'">'+(t?{high:"YÜKSEK",medium:"ORTA",low:"DÜŞÜK"}[mc.robustness]:mc.robustness.toUpperCase())+'</b></span></div>';
h+='<div class="mc-ci-labels"><span class="mc-ci-label ci95">'+(t?"%95 GA":"95% CI")+': ['+mc.ci95[0]+' — '+mc.ci95[1]+']</span><span class="mc-ci-label ci80">'+(t?"%80 GA":"80% CI")+': ['+mc.ci80[0]+' — '+mc.ci80[1]+']</span></div>';
h+='<div class="mc-note">'+(t?"N="+mc.iterations+" iterasyon. Ağırlıklara ±%15, verilere ±%10 pertürbasyon.":"N="+mc.iterations+" iterations. ±15% weight, ±10% data perturbation.")+'</div></div>'}

// IR Theories
h+='<div style="background:var(--card-bg);border:1px solid var(--border);border-left:3px solid var(--purple);border-radius:2px;padding:16px;margin-bottom:8px">';
h+='<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span style="color:var(--purple)">'+(ICONS&&ICONS.theory?ICONS.theory:"🎓")+'</span><span style="font-family:var(--font-mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:var(--purple)">'+(t?"Uİ Teori Entegratörleri":"IR Theory Integrators")+'</span><span style="margin-left:auto;font-family:var(--font-mono);font-size:.8rem;font-weight:700;color:'+(adv.scoreDelta>=0?"var(--green)":"var(--neg)")+'">'+(adv.scoreDelta>0?"+":"")+adv.scoreDelta+'</span></div>';
h+='<div class="eng-score-compare"><div class="eng-score-box"><span class="eng-score-label">'+(t?"Temel":"Base")+'</span><span class="eng-score-num">'+adv.baseScore+'</span></div><div class="eng-score-arrow">→</div><div class="eng-score-box advanced"><span class="eng-score-label">'+(t?"Gelişmiş":"Advanced")+'</span><span class="eng-score-num">'+adv.advancedScore+'</span></div></div>';

// Democratic Peace
var dp=adv.democraticPeace;if(dp){var rC={very_low:"var(--green)",baseline:"var(--t3)",elevated:"var(--amber)",highest:"var(--neg)"}[dp.warRisk]||"var(--t3)";h+='<div class="eng-theory-block"><div class="eng-theory-name">'+(t?"Demokratik Barış":"Democratic Peace")+' <span class="eng-theory-ref">(Doyle 1983)</span></div><div class="eng-regime-pair"><span class="eng-regime-tag">'+cN(codeA)+': '+fmtRegime(dp.regimeA,t)+'</span><span class="eng-regime-vs">×</span><span class="eng-regime-tag">'+cN(codeB)+': '+fmtRegime(dp.regimeB,t)+'</span></div><div class="eng-theory-effect">'+(t?"Bonus":"Bonus")+': <span style="color:'+(dp.peaceBonus>0?"var(--green)":"var(--neg)")+'">'+(dp.peaceBonus>0?"+":"")+dp.peaceBonus+'</span> | '+(t?"Savaş Riski":"War Risk")+': <span style="color:'+rC+'">'+dp.warRisk.replace(/_/g," ").toUpperCase()+'</span></div><div class="eng-theory-text">'+dp.explanation+'</div></div>'}

// Power Transition
var pt=adv.powerTransition;if(pt){var tC=pt.trapActive?"var(--neg)":pt.phase==="convergence"?"var(--amber)":"var(--green)";h+='<div class="eng-theory-block'+(pt.trapActive?" trap-active":"")+'"><div class="eng-theory-name">'+(t?"Güç Geçişi / Thucydides":"Power Transition / Thucydides")+' <span class="eng-theory-ref">(Organski 1958, Allison 2017)</span></div><div class="eng-theory-effect">'+(t?"Güç Oranı":"Power Ratio")+': <b>'+pt.ratio+'</b> | '+(t?"Faz":"Phase")+': <span style="color:'+tC+'">'+pt.phase.toUpperCase()+'</span> | '+(t?"Risk":"Risk")+': <b>'+pt.transitionRisk+'</b></div>';if(pt.trapActive)h+='<div class="eng-trap-warn">⚠ '+(t?"THUCYDIDES TUZAĞI AKTİF — 16 vakadan 12'si savaş":"THUCYDIDES TRAP ACTIVE — 12/16 cases = war")+'</div>';h+='<div class="eng-theory-text">'+pt.explanation+'</div></div>'}

// Regime
var ri=adv.regimeInteraction;if(ri){h+='<div class="eng-theory-block"><div class="eng-theory-name">'+(t?"Rejim Etkileşimi":"Regime Interaction")+'</div><div class="eng-regime-pair"><span class="eng-regime-tag">'+fmtRegime(ri.regimeA,t)+'</span><span class="eng-regime-vs">×</span><span class="eng-regime-tag">'+fmtRegime(ri.regimeB,t)+'</span></div><div class="eng-theory-effect">'+(t?"İşbirliği":"Coop")+': <span style="color:'+(ri.coopMod>0?"var(--green)":"var(--neg)")+'">'+(ri.coopMod>0?"+":"")+ri.coopMod+'</span> | '+(t?"Çatışma":"Conflict")+': <span style="color:'+(ri.conflictMod>0?"var(--neg)":"var(--green)")+'">'+(ri.conflictMod>0?"+":"")+ri.conflictMod+'</span></div></div>'}
h+='</div>';

// Nuclear
var nuc=adv.nuclear;if(nuc&&nuc.type!=="non_nuclear"){var nC=nuc.stabilityIndex>70?"var(--green)":nuc.stabilityIndex>40?"var(--amber)":"var(--neg)";h+='<div style="background:var(--card-bg);border:1px solid var(--border);border-left:3px solid '+nC+';border-radius:2px;padding:16px;margin-bottom:8px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span style="color:'+nC+'">☢</span><span style="font-family:var(--font-mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:'+nC+'">'+(t?"Nükleer Caydırıcılık":"Nuclear Deterrence")+'</span><span style="margin-left:auto;font-family:var(--font-mono);font-size:1rem;font-weight:700;color:'+nC+'">'+nuc.stabilityIndex+'</span></div>';if(nuc.type==="nuclear_dyad"){h+='<div class="nuc-stats"><span class="nuc-stat">MAD: <b style="color:'+(nuc.mad?"var(--green)":"var(--neg)")+'">'+(nuc.mad?"✓":"✗")+'</b></span><span class="nuc-stat">FSI: <b style="color:'+nC+'">'+nuc.firstStrikeStability+'</b></span><span class="nuc-stat">'+(t?"Başlık Oranı":"WH Ratio")+': <b>'+nuc.warheadRatio+'</b></span></div>'}h+='<div class="eng-theory-text">'+nuc.explanation+'</div></div>'}

// Geo-Strategic
var geo=adv.geoStrategic;if(geo){h+='<div style="background:var(--card-bg);border:1px solid var(--border);border-left:3px solid var(--cyan);border-radius:2px;padding:16px;margin-bottom:8px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span style="color:var(--cyan)">'+(ICONS&&ICONS.geo?ICONS.geo:"🌐")+'</span><span style="font-family:var(--font-mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:var(--cyan)">'+(t?"Jeo-Stratejik":"Geo-Strategic")+'</span><span style="margin-left:auto;font-family:var(--font-mono);font-size:.8rem;color:var(--t1)">'+geo.distance.toLocaleString()+' km</span></div>';
h+='<div class="geo-stats"><span class="geo-stat">'+(t?"Mesafe":"Distance")+': '+geo.distance+'km</span><span class="geo-stat">'+(t?"Yakınlık":"Proximity")+': '+(geo.proximityEffect>0?"+":"")+geo.proximityEffect+'</span><span class="geo-stat">'+(t?"Projeksiyon Farkı":"Proj. Gap")+': '+(geo.projectionGap>0?"+":"")+geo.projectionGap+'</span></div>';
if(geo.chokepoints.length>0){h+='<div class="geo-choke-title">'+(t?"Kritik Boğazlar":"Chokepoints")+'</div>';geo.chokepoints.forEach(function(cp){var sC=cp.status.indexOf("closed")>=0?"var(--neg)":cp.status.indexOf("disrupted")>=0?"var(--amber)":"var(--green)";h+='<div class="geo-choke-row"><span class="geo-choke-name">'+cp.name+'</span><span class="geo-choke-status" style="color:'+sC+'">'+cp.status.replace(/_/g," ").toUpperCase()+'</span>';if(cp.leverage)h+='<span class="geo-choke-leverage">'+(t?"Kaldıraç":"Leverage")+': '+(C[cp.leverage]?C[cp.leverage].n:cp.leverage)+'</span>';h+='</div>'})}
h+='<div class="geo-proj-compare"><div class="geo-proj-row"><span class="geo-proj-name">'+cN(codeA)+'</span><div class="geo-proj-bar"><div class="geo-proj-fill" style="width:'+geo.projectionA+'%"></div></div><span class="geo-proj-val">'+geo.projectionA+'</span></div><div class="geo-proj-row"><span class="geo-proj-name">'+cN(codeB)+'</span><div class="geo-proj-bar"><div class="geo-proj-fill" style="width:'+geo.projectionB+'%"></div></div><span class="geo-proj-val">'+geo.projectionB+'</span></div></div></div>'}

// Cascade
var cas=adv.cascade;if(cas&&cas.secondOrder&&cas.secondOrder.length>0){h+='<div style="background:var(--card-bg);border:1px solid var(--border);border-left:3px solid var(--amber);border-radius:2px;padding:16px;margin-bottom:8px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span style="color:var(--amber)">'+(ICONS&&ICONS.cascade?ICONS.cascade:"🔗")+'</span><span style="font-family:var(--font-mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:var(--amber)">'+(t?"Kaskad Etkileri":"Cascade Effects")+'</span><span style="margin-left:auto;font-family:var(--font-mono);font-size:.7rem;color:var(--t2)">'+cas.secondOrder.length+' '+(t?"ülke":"countries")+'</span></div>';
h+='<div class="cas-title">'+(t?"2. Derece":"2nd Order")+'</div>';cas.secondOrder.slice(0,6).forEach(function(eff){var iC=eff.netImpact>0?"var(--green)":eff.netImpact<-3?"var(--neg)":"var(--amber)";h+='<div class="cas-row"><img src="https://flagcdn.com/w20/'+(_flagMap[eff.country]||eff.country.toLowerCase())+'.png" width="14" height="9"> <span class="cas-name">'+eff.name+'</span><span class="cas-impact" style="color:'+iC+'">'+(eff.netImpact>0?"+":"")+eff.netImpact+'</span><span class="cas-pull">→ '+(C[eff.pullDirection]?C[eff.pullDirection].n:eff.pullDirection)+'</span>';if(eff.crossPressure>.4)h+='<span class="cas-pressure">⚠</span>';h+='</div>'});h+='</div>'}

// Alliance Reliability
var al=adv.allianceReliability;if(al&&al.sharedAlliances&&al.sharedAlliances.length>0){h+='<div style="background:var(--card-bg);border:1px solid var(--border);border-left:3px solid var(--green);border-radius:2px;padding:16px;margin-bottom:8px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span style="color:var(--green)">'+(ICONS&&ICONS.alliance?ICONS.alliance:"🛡")+'</span><span style="font-family:var(--font-mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:var(--green)">'+(t?"İttifak Güvenilirliği":"Alliance Reliability")+'</span><span style="margin-left:auto;font-family:var(--font-mono);font-size:.8rem;font-weight:700;color:var(--t1)">'+al.avgReliability+'</span></div>';
h+='<div class="al-bond">'+(t?"Bağ":"Bond")+': <b>'+al.bondStrength.toUpperCase()+'</b></div>';
al.sharedAlliances.forEach(function(a){var rC=a.reliability>70?"var(--green)":a.reliability>40?"var(--amber)":"var(--neg)";var sC={low:"var(--green)",medium:"var(--amber)",high:"#ff6600",critical:"var(--neg)"}[a.stress]||"var(--t3)";h+='<div class="al-row"><span class="al-name">'+a.name+'</span><div class="al-bar"><div class="al-fill" style="width:'+a.reliability+'%;background:'+rC+'"></div></div><span class="al-val" style="color:'+rC+'">'+a.reliability+'</span><span class="al-stress" style="color:'+sC+'">'+(t?"Stres":"Stress")+': '+a.stress+'</span></div>'});h+='</div>'}

// Data Freshness
var df=adv.dataFreshness;if(df){var aC=df.average>.7?"var(--green)":df.average>.5?"var(--amber)":"var(--neg)";h+='<div style="background:var(--card-bg);border:1px solid var(--border);border-left:3px solid var(--t3);border-radius:2px;padding:16px;margin-bottom:8px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span>📅</span><span style="font-family:var(--font-mono);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:var(--t3)">'+(t?"Veri Tazeliği":"Data Freshness")+'</span><span style="margin-left:auto;font-family:var(--font-mono);font-size:.8rem;font-weight:700;color:'+aC+'">'+Math.round(df.average*100)+'%</span></div>';
h+='<div class="fresh-rows">';Object.entries(df.sources).sort(function(a,b){return a[1].freshness-b[1].freshness}).forEach(function(e){var fC=e[1].freshness>.7?"var(--green)":e[1].freshness>.5?"var(--amber)":"var(--neg)";h+='<div class="fresh-row"><span class="fresh-label">'+e[0]+'</span><div class="fresh-bar"><div class="fresh-fill" style="width:'+(e[1].freshness*100)+'%;background:'+fC+'"></div></div><span class="fresh-val" style="color:'+fC+'">'+Math.round(e[1].freshness*100)+'% ('+e[1].daysOld+'d)</span></div>'});h+='</div></div>'}

return h}

function fmtRegime(r,t){var m=t?{full_democracy:"Tam Demokrasi",flawed_democracy:"Kusurlu Demokrasi",hybrid_regime:"Hibrit Rejim",competitive_authoritarian:"Rekabetçi Otoriter",closed_autocracy:"Kapalı Otokrasi"}:{full_democracy:"Full Democracy",flawed_democracy:"Flawed Democracy",hybrid_regime:"Hybrid Regime",competitive_authoritarian:"Competitive Auth.",closed_autocracy:"Closed Autocracy"};return m[r]||r}
