// AXIS — Advanced Analytical Engine v2.0
// Monte Carlo, Cascade, Nuclear Deterrence, Power Projection, Regime Interaction
// © 2026 Kuzey Çağan Gebrecioğlu

function monteCarloAxis(codeA,codeB,iterations){iterations=iterations||300;var scores=[];for(var i=0;i<iterations;i++){var pw={};var wt=0;var baseWeights=typeof getActiveWeights==="function"?getActiveWeights():defaultWeights;Object.keys(baseWeights).forEach(function(k){var n=1+(Math.random()-.5)*.3;pw[k]=baseWeights[k]*n;wt+=pw[k]});Object.keys(pw).forEach(function(k){pw[k]/=wt});var r=typeof computeAxis==="function"?computeAxis(codeA,codeB):null;if(!r){scores.push(50);continue}var noise=function(){return 1+(Math.random()-.5)*.2};var comp=((r.military?r.military.score:50)*noise())*(pw.military||.16)+((r.economic?r.economic.score:50)*noise())*(pw.economic||.2)+((r.lobby?r.lobby.score:50)*noise())*(pw.lobby||.1)+((r.cultural?r.cultural.score:50)*noise())*(pw.cultural||.1)+((r.strategic?r.strategic.score:50)*noise())*(pw.strategic||.2)+((r.behavioral?r.behavioral.score:50)*noise())*(pw.behavioral||.12)+(50*noise())*(pw.media||.12);scores.push(Math.max(0,Math.min(100,comp)))}scores.sort(function(a,b){return a-b});var mean=scores.reduce(function(s,v){return s+v},0)/scores.length;var sd=Math.sqrt(scores.reduce(function(s,v){return s+Math.pow(v-mean,2)},0)/scores.length);return{mean:Math.round(mean*10)/10,stdDev:Math.round(sd*10)/10,ci95:[Math.round(scores[Math.floor(scores.length*.025)]*10)/10,Math.round(scores[Math.floor(scores.length*.975)]*10)/10],ci80:[Math.round(scores[Math.floor(scores.length*.1)]*10)/10,Math.round(scores[Math.floor(scores.length*.9)]*10)/10],robustness:sd<5?"high":sd<10?"medium":"low",iterations:iterations}}

var INTERACTION_MATRIX={mil:{econ:-.15,cult:-.1,strat:.2,gdelt:-.2},econ:{mil:.1,lobby:.15,strat:.15,gdelt:.15},lobby:{econ:.1,cult:.1,beh:.1},cult:{lobby:.1,beh:.15,strat:.1},strat:{mil:.15,econ:.1,beh:.1,gdelt:.1},beh:{cult:.1,strat:.1},gdelt:{mil:-.1,strat:-.05}};

function applyInteractionEffects(layers){var adj={};var dev={};Object.keys(layers).forEach(function(k){adj[k]=layers[k];dev[k]=(layers[k]-50)/50});Object.keys(adj).forEach(function(tgt){var mod=0;Object.keys(INTERACTION_MATRIX).forEach(function(src){if(src===tgt||!INTERACTION_MATRIX[src][tgt])return;mod+=dev[src]*(INTERACTION_MATRIX[src][tgt]||0)*15});adj[tgt]=Math.max(0,Math.min(100,adj[tgt]+mod))});return adj}

var IR_THEORIES={democraticPeace:function(codeA,codeB){var dA=C[codeA]?C[codeA].dem:5,dB=C[codeB]?C[codeB].dem:5;var rA=dA>7?"democracy":dA>4?"anocracy":"autocracy";var rB=dB>7?"democracy":dB>4?"anocracy":"autocracy";var bonus=0,risk="baseline",t=lang==="tr";if(rA==="democracy"&&rB==="democracy"){bonus=15;risk="very_low"}else if(rA==="autocracy"&&rB==="autocracy"){bonus=-5;risk="elevated"}else{bonus=-10;risk="highest"}return{peaceBonus:bonus,warRisk:risk,regimeA:rA,regimeB:rB,explanation:risk==="very_low"?(t?"İki demokrasi: Demokratik Barış Teorisi güçlü uygulanır (Doyle 1983)":"Two democracies: Democratic Peace Theory strongly applies (Doyle 1983)"):risk==="highest"?(t?"Karışık rejim çifti: EN YÜKSEK savaş riski (Mansfield & Snyder 2005)":"Mixed regime dyad: HIGHEST war risk (Mansfield & Snyder 2005)"):(t?"İki otokrasi: Otokratik barış argümanı zayıf":"Two autocracies: Autocratic peace argument is weak")}},

powerTransition:function(codeA,codeB){var gdpA=C[codeA]?C[codeA].gdp:1000,gdpB=C[codeB]?C[codeB].gdp:1000;var milA=C[codeA]?C[codeA].mil:50,milB=C[codeB]?C[codeB].mil:50;var pA=gdpA*.6+milA*10*.4,pB=gdpB*.6+milB*10*.4;var ratio=Math.min(pA,pB)/Math.max(pA,pB);var stronger=pA>pB?codeA:codeB,weaker=pA>pB?codeB:codeA;var risk=0,phase="",trap=false,t=lang==="tr";if(ratio>.8){risk=25;phase="parity";trap=true}else if(ratio>.6){risk=15;phase="convergence"}else if(ratio>.3){risk=5;phase="asymmetric"}else{risk=0;phase="dominant"}return{transitionRisk:risk,ratio:Math.round(ratio*100)/100,phase:phase,stronger:stronger,weaker:weaker,trapActive:trap,explanation:trap?(t?"GÜÇ PARİTESİ — Thucydides Tuzağı aktif (Allison 2017)":"POWER PARITY — Thucydides Trap active (Allison 2017)"):phase==="convergence"?(t?"YAKINLAŞMA — hegemon önleyici saldırı güdüsü artabilir":"CONVERGENCE — hegemon preventive war incentive may increase"):(t?"Asimetrik güç ilişkisi":"Asymmetric power relationship")}}};

function computeCascadeEffects(codeA,codeB,axisScore){var codes=Object.keys(C);var effects=[];codes.forEach(function(third){if(third===codeA||third===codeB)return;var tA=50,tB=50;try{if(typeof computeAxis==="function"){tA=computeAxis(third,codeA).composite;tB=computeAxis(third,codeB).composite}}catch(e){}var aAlign=tA/100,bAlign=tB/100;var crossP=Math.min(aAlign,bAlign)*(100-(axisScore||50))/100;var aGrav=aAlign*(C[codeA]?C[codeA].gdp:1000),bGrav=bAlign*(C[codeB]?C[codeB].gdp:1000);var pull=aGrav>bGrav?codeA:codeB;var pullStr=Math.abs(aGrav-bGrav)/Math.max(aGrav,bGrav)*20;var impact=Math.round(crossP*-5+pullStr*(aGrav>bGrav?1:-1)*.5);if(Math.abs(impact)>=2||crossP>.3)effects.push({country:third,name:C[third]?C[third].n:third,crossPressure:Math.round(crossP*100)/100,pullDirection:pull,netImpact:impact})});return{secondOrder:effects.sort(function(a,b){return Math.abs(b.netImpact)-Math.abs(a.netImpact)}).slice(0,8)}}

var GEO_CENTERS={US:[38.9,-77],CN:[39.9,116.4],JP:[35.7,139.7],DE:[52.5,13.4],GB:[51.5,-.1],FR:[48.9,2.3],IN:[28.6,77.2],IT:[41.9,12.5],BR:[-15.8,-47.9],CA:[45.4,-75.7],KR:[37.6,127],RU:[55.8,37.6],AU:[-35.3,149.1],MX:[19.4,-99.1],ID:[-6.2,106.8],SA:[24.7,46.7],TR:[39.9,32.9],AR:[-34.6,-58.4],ZA:[-25.7,28.2]};

var CHOKEPOINTS={hormuz:{name:"Strait of Hormuz",controllers:["IR"],affected:["SA","AE","KW"],status:"closed_2026"},malacca:{name:"Strait of Malacca",controllers:["MY","SG","ID"],affected:["CN","JP","KR","IN"],status:"open"},suez:{name:"Suez Canal",controllers:["EG"],affected:["GB","FR","DE","IT","CN"],status:"disrupted_houthi"},bosporus:{name:"Turkish Straits",controllers:["TR"],affected:["RU"],status:"open"},taiwan:{name:"Taiwan Strait",controllers:["TW","CN"],affected:["JP","KR","US"],status:"tense"}};

var POWER_PROJECTION={US:100,CN:55,GB:50,FR:45,RU:35,IN:30,TR:28,JP:25,IT:22,AU:20,KR:18,SA:15,DE:15,BR:12,CA:12,ID:10,ZA:8,MX:5,AR:5};

function haversine(lat1,lon1,lat2,lon2){var R=6371;var dLat=(lat2-lat1)*Math.PI/180;var dLon=(lon2-lon1)*Math.PI/180;var a=Math.pow(Math.sin(dLat/2),2)+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.pow(Math.sin(dLon/2),2);return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}

function computeGeoStrategic(codeA,codeB){var cA=GEO_CENTERS[codeA],cB=GEO_CENTERS[codeB];if(!cA||!cB)return null;var dist=Math.round(haversine(cA[0],cA[1],cB[0],cB[1]));var rcp=[];Object.entries(CHOKEPOINTS).forEach(function(e){var cp=e[1];var aA=cp.controllers.indexOf(codeA)>=0||cp.affected.indexOf(codeA)>=0;var aB=cp.controllers.indexOf(codeB)>=0||cp.affected.indexOf(codeB)>=0;if(aA||aB)rcp.push({name:cp.name,status:cp.status,affectsA:aA,affectsB:aB,mutual:aA&&aB,leverage:cp.controllers.indexOf(codeA)>=0&&cp.affected.indexOf(codeB)>=0?codeA:cp.controllers.indexOf(codeB)>=0&&cp.affected.indexOf(codeA)>=0?codeB:null})});var pA=POWER_PROJECTION[codeA]||0,pB=POWER_PROJECTION[codeB]||0;var proxEffect=dist<1000?10:dist<3000?5:dist>12000?-5:0;return{distance:dist,proximityEffect:proxEffect,chokepoints:rcp,projectionA:pA,projectionB:pB,projectionGap:pA-pB}}

var NUCLEAR_DATA={US:{warheads:5550,triad:true,secondStrike:"assured",doctrine:"flexible_response",bmd:true},RU:{warheads:6257,triad:true,secondStrike:"assured",doctrine:"escalate_to_deescalate",bmd:true},CN:{warheads:500,triad:true,secondStrike:"developing_assured",doctrine:"no_first_use",bmd:false},GB:{warheads:225,triad:false,secondStrike:"minimum",doctrine:"minimum_deterrence",bmd:false},FR:{warheads:290,triad:false,secondStrike:"minimum",doctrine:"forward_deterrence_2026",bmd:false},IN:{warheads:172,triad:true,secondStrike:"developing",doctrine:"no_first_use",bmd:false}};

function computeNuclearDeterrence(codeA,codeB){var nA=NUCLEAR_DATA[codeA],nB=NUCLEAR_DATA[codeB];var t=lang==="tr";if(!nA&&!nB)return{type:"non_nuclear",stabilityIndex:50,explanation:t?"Nükleer değil — konvansiyonel caydırıcılık":"Non-nuclear dyad — conventional deterrence"};if(nA&&nB){var ratio=Math.min(nA.warheads,nB.warheads)/Math.max(nA.warheads,nB.warheads);var bSS=nA.secondStrike.indexOf("assured")>=0&&nB.secondStrike.indexOf("assured")>=0;var bT=nA.triad&&nB.triad;var fsi=50;if(bSS)fsi+=25;if(bT)fsi+=10;if(ratio>.5)fsi+=10;if((nA.bmd&&!nB.bmd)||(nB.bmd&&!nA.bmd))fsi-=15;if(nA.doctrine==="escalate_to_deescalate"||nB.doctrine==="escalate_to_deescalate")fsi-=15;fsi=Math.max(0,Math.min(100,fsi));return{type:"nuclear_dyad",mad:bSS,firstStrikeStability:fsi,warheadRatio:Math.round(ratio*100)/100,stabilityIndex:fsi,explanation:fsi>70?(t?"Yüksek nükleer istikrar — MAD geçerli":"High nuclear stability — MAD applies"):fsi>40?(t?"Orta istikrar — asimetrik kapasiteler kriz riski":"Moderate stability — asymmetric capabilities crisis risk"):(t?"DÜŞÜK İSTİKRAR — nükleer tırmanma riski yüksek":"LOW STABILITY — nuclear escalation risk elevated")}}return{type:"asymmetric_nuclear",nuclearState:nA?codeA:codeB,stabilityIndex:35,explanation:t?"Nükleer asimetri — genişletilmiş caydırıcılık geçerli":"Nuclear asymmetry — extended deterrence applies"}}

function getRegimeType(code){var dem=C[code]?C[code].dem:5;var fh=C[code]?C[code].fh:50;var comb=dem*6+fh*.4;if(comb>70)return"full_democracy";if(comb>55)return"flawed_democracy";if(comb>35)return"hybrid_regime";if(comb>20)return"competitive_authoritarian";return"closed_autocracy"}

var REGIME_INTERACTION={"full_democracy":{"full_democracy":{coopMod:15,conflictMod:-20},"flawed_democracy":{coopMod:8,conflictMod:-10},"hybrid_regime":{coopMod:-3,conflictMod:5},"competitive_authoritarian":{coopMod:-8,conflictMod:10},"closed_autocracy":{coopMod:-12,conflictMod:15}},"flawed_democracy":{"flawed_democracy":{coopMod:8,conflictMod:-8},"hybrid_regime":{coopMod:0,conflictMod:0},"competitive_authoritarian":{coopMod:-5,conflictMod:8},"closed_autocracy":{coopMod:-8,conflictMod:10}},"hybrid_regime":{"hybrid_regime":{coopMod:3,conflictMod:-3},"competitive_authoritarian":{coopMod:5,conflictMod:-3},"closed_autocracy":{coopMod:0,conflictMod:0}},"competitive_authoritarian":{"competitive_authoritarian":{coopMod:5,conflictMod:-5},"closed_autocracy":{coopMod:3,conflictMod:-3}},"closed_autocracy":{"closed_autocracy":{coopMod:8,conflictMod:-5}}};

function getRegimeInteraction(codeA,codeB){var rA=getRegimeType(codeA),rB=getRegimeType(codeB);var int=(REGIME_INTERACTION[rA]&&REGIME_INTERACTION[rA][rB])||(REGIME_INTERACTION[rB]&&REGIME_INTERACTION[rB][rA])||{coopMod:0,conflictMod:0};return{coopMod:int.coopMod,conflictMod:int.conflictMod,regimeA:rA,regimeB:rB}}

var DATA_FRESHNESS={gdp:{lastUpdate:"2024-06",halfLife:365},military:{lastUpdate:"2024-12",halfLife:365},trade:{lastUpdate:"2024-06",halfLife:180},hofstede:{lastUpdate:"2023-01",halfLife:3650},unVoting:{lastUpdate:"2024-09",halfLife:365},gdelt:{lastUpdate:"live",halfLife:1},behavioral:{lastUpdate:"2026-03",halfLife:180}};

function computeTemporalDecay(key){var src=DATA_FRESHNESS[key];if(!src||src.lastUpdate==="live")return{freshness:1,daysOld:0};var now=new Date(2026,2,31);var parts=src.lastUpdate.split("-");var upd=new Date(+parts[0],(+parts[1])-1,15);var days=Math.round((now-upd)/(864e5));return{freshness:Math.round(Math.exp(-.693*days/src.halfLife)*1000)/1000,daysOld:days}}

function getOverallDataFreshness(){var total=0,count=0,results={};Object.keys(DATA_FRESHNESS).forEach(function(k){var d=computeTemporalDecay(k);results[k]=d;total+=d.freshness;count++});return{sources:results,average:Math.round(total/count*1000)/1000}}

var ALLIANCE_RELIABILITY={NATO:{reliability:82,stress:"high"},AUKUS:{reliability:78,stress:"medium"},"Five Eyes":{reliability:92,stress:"low"},Quad:{reliability:55,stress:"high"},EU:{reliability:70,stress:"medium"},BRICS:{reliability:30,stress:"critical"},SCO:{reliability:40,stress:"high"},ASEAN:{reliability:45,stress:"medium"}};

function computeAllianceReliability(codeA,codeB){var alA=C[codeA]?C[codeA].al:[];var alB=C[codeB]?C[codeB].al:[];var shared=alA.filter(function(a){return alB.indexOf(a)>=0});if(shared.length===0)return{sharedAlliances:[],avgReliability:0,bondStrength:"none"};var total=0;var details=[];shared.forEach(function(name){var data=ALLIANCE_RELIABILITY[name];var rel=data?data.reliability:50;total+=rel;details.push({name:name,reliability:rel,stress:data?data.stress:"unknown"})});var avg=Math.round(total/shared.length);return{sharedAlliances:details,avgReliability:avg,bondStrength:avg>75?"strong":avg>50?"moderate":avg>25?"weak":"nominal"}}

function computeAxisAdvanced(codeA,codeB){var base=50;try{if(typeof computeAxis==="function")base=computeAxis(codeA,codeB).composite}catch(e){}var result={baseScore:base};result.monteCarlo=monteCarloAxis(codeA,codeB,300);result.democraticPeace=IR_THEORIES.democraticPeace(codeA,codeB);result.powerTransition=IR_THEORIES.powerTransition(codeA,codeB);result.regimeInteraction=getRegimeInteraction(codeA,codeB);result.nuclear=computeNuclearDeterrence(codeA,codeB);result.geoStrategic=computeGeoStrategic(codeA,codeB);result.cascade=computeCascadeEffects(codeA,codeB,base);result.allianceReliability=computeAllianceReliability(codeA,codeB);result.dataFreshness=getOverallDataFreshness();
var adv=base;adv+=result.democraticPeace.peaceBonus;adv-=result.powerTransition.transitionRisk*.3;adv+=result.regimeInteraction.coopMod*.5;if(result.geoStrategic)adv+=result.geoStrategic.proximityEffect*.3;adv=Math.max(0,Math.min(100,Math.round(adv)));result.advancedScore=adv;result.scoreDelta=adv-base;
var t=lang==="tr";result.warnings=[];if(result.powerTransition.trapActive)result.warnings.push(t?"⚠ THUCYDIDES TUZAĞI AKTİF":"⚠ THUCYDIDES TRAP ACTIVE");if(result.nuclear.stabilityIndex<40)result.warnings.push(t?"☢ DÜŞÜK NÜKLEER İSTİKRAR":"☢ LOW NUCLEAR STABILITY");if(result.democraticPeace.warRisk==="highest")result.warnings.push(t?"⚔ KARIŞIK REJİM — yüksek savaş riski":"⚔ MIXED REGIME — highest war risk");if(result.monteCarlo.robustness==="low")result.warnings.push(t?"📊 DÜŞÜK SKOR SAĞLAMLIĞI":"📊 LOW SCORE ROBUSTNESS");var closedCP=(result.geoStrategic?result.geoStrategic.chokepoints:[]).filter(function(cp){return cp.status.indexOf("closed")>=0||cp.status.indexOf("disrupted")>=0});if(closedCP.length>0)result.warnings.push((t?"🚢 BOĞAZ KAPATILMIŞ: ":"🚢 CHOKEPOINT DISRUPTED: ")+closedCP.map(function(cp){return cp.name}).join(", "));if(result.dataFreshness.average<.6)result.warnings.push(t?"📅 VERİ ESKİMESİ UYARISI":"📅 DATA STALENESS WARNING");return result}
