// AXIS — Media Bias Awareness Module
// © 2026 Kuzey Çağan Gebrecioğlu

var MEDIA_BIAS={gdeltBiases:{en:["English-language media overrepresentation (~65% of sources)","Western agency wire services dominate (AP, Reuters, AFP)","Under-coverage of non-Latin script media","Tone algorithm trained primarily on English text","Recency bias — breaking news overweights negative events","Volume ≠ importance"],tr:["İngilizce medya aşırı temsil (~%65)","Batılı ajans haberleri baskın (AP, Reuters, AFP)","Latin dışı alfabe medyası yetersiz kapsam","Ton algoritması İngilizce metin üzerinde eğitilmiş","Güncellik yanlılığı — son dakika olumsuz olayları aşırı ağırlıklandırıyor","Hacim ≠ önem"]},pairSpecificBiases:{"US_CN":{en:"US-China coverage heavily influenced by US media framing. GDELT tone likely reflects Western perception.",tr:"ABD-Çin haberleri ABD medya çerçevelemesinden etkilenir. GDELT tonu Batı algısını yansıtır."},"CN_RU":{en:"Chinese and Russian media largely absent from GDELT English corpus.",tr:"Çin ve Rus medyası GDELT İngilizce derleminde büyük ölçüde eksik."},"RU_US":{en:"GDELT captures Western narrative. Russian domestic narrative absent.",tr:"GDELT Batı anlatısını yakalar. Rus iç anlatısı eksik."},"SA_IR":{en:"Both countries have restricted press. GDELT relies on regional English outlets.",tr:"Her iki ülkenin kısıtlı basını var. GDELT bölgesel İngilizce yayınlara dayanıyor."},"IN_CN":{en:"Indian English media overrepresented vs Chinese sources.",tr:"Hint İngilizce medya Çin kaynaklarına göre aşırı temsil."}}};

function renderMediaBiasWarning(codeA,codeB){var t=lang==="tr";var pk1=codeA+"_"+codeB,pk2=codeB+"_"+codeA;var specific=MEDIA_BIAS.pairSpecificBiases[pk1]||MEDIA_BIAS.pairSpecificBiases[pk2];var h='<div class="bias-warning"><div class="bias-title">⚠ '+(t?"GDELT MEDYA YANLILIK UYARISI":"GDELT MEDIA BIAS ADVISORY")+'</div>';
if(specific)h+='<div class="bias-specific">'+(t?specific.tr:specific.en)+'</div>';
h+='<div class="bias-general-title">'+(t?"Genel GDELT Yanlılıkları:":"General GDELT Biases:")+'</div><div class="bias-list">';
(t?MEDIA_BIAS.gdeltBiases.tr:MEDIA_BIAS.gdeltBiases.en).forEach(function(b){h+='<div class="bias-item">'+b+'</div>'});
h+='</div><div class="bias-note">'+(t?"GDELT katmanı (%12) uluslararası medya ikliminin yaklaşık göstergesidir, kesin ölçü değil.":"The GDELT layer (12%) is an approximate indicator, not a precise measure.")+'</div></div>';return h}
